[project]
name = "store"
version = "0.1.0"
description = "A function for performing mathematical calculations."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beamlit>=0.0.41",
]
